<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="27" ignored="0" total="112" passed="85">
  <reporter-output>
  </reporter-output>
  <suite name="Command line suite" duration-ms="381" started-at="2019-01-08T08:03:50Z" finished-at="2019-01-08T08:03:50Z">
    <groups>
      <group name="group 2">
        <method signature="SumCalculatorTest.testSum1(long, long, long)[pri:0, instance:kz.epam.unittesting.tests.SumCalculatorTest@19593091]" name="testSum1" class="kz.epam.unittesting.tests.SumCalculatorTest"/>
      </group> <!-- group 2 -->
      <group name="group 1">
        <method signature="SumCalculatorTest.testSum(long, long, long)[pri:0, instance:kz.epam.unittesting.tests.SumCalculatorTest@19593091]" name="testSum" class="kz.epam.unittesting.tests.SumCalculatorTest"/>
      </group> <!-- group 1 -->
    </groups>
    <test name="Command line test" duration-ms="381" started-at="2019-01-08T08:03:50Z" finished-at="2019-01-08T08:03:50Z">
      <class name="kz.epam.unittesting.tests.MultDoubleCalculatorTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:kz.epam.unittesting.tests.MultDoubleCalculatorTest@264c5d07]" name="setUp" is-config="true" duration-ms="1" started-at="2019-01-08T16:03:50Z" finished-at="2019-01-08T16:03:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="multTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.MultDoubleCalculatorTest@264c5d07]" name="multTest" duration-ms="1" started-at="2019-01-08T16:03:50Z" data-provider="multDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1.1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[2.2]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Invalid result of multiplication:  expected [2.2] but found [2.0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Invalid result of multiplication:  expected [2.2] but found [2.0]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at kz.epam.unittesting.tests.MultDoubleCalculatorTest.multTest(MultDoubleCalculatorTest.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- multTest -->
        <test-method status="FAIL" signature="multTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.MultDoubleCalculatorTest@264c5d07]" name="multTest" duration-ms="1" started-at="2019-01-08T16:03:50Z" data-provider="multDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[5.5]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[5.5]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[30.25]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Invalid result of multiplication:  expected [30.25] but found [30.0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Invalid result of multiplication:  expected [30.25] but found [30.0]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at kz.epam.unittesting.tests.MultDoubleCalculatorTest.multTest(MultDoubleCalculatorTest.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- multTest -->
        <test-method status="PASS" signature="multTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.MultDoubleCalculatorTest@264c5d07]" name="multTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="multDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[10]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[-15.1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[-151]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- multTest -->
        <test-method status="FAIL" signature="multTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.MultDoubleCalculatorTest@264c5d07]" name="multTest" duration-ms="2" started-at="2019-01-08T16:03:50Z" data-provider="multDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[4.77]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[4.78]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[22.8006]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Invalid result of multiplication:  expected [22.8006] but found [22.0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Invalid result of multiplication:  expected [22.8006] but found [22.0]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at kz.epam.unittesting.tests.MultDoubleCalculatorTest.multTest(MultDoubleCalculatorTest.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- multTest -->
        <test-method status="PASS" signature="multTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.MultDoubleCalculatorTest@264c5d07]" name="multTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="multDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[-10]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[-15]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[150]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- multTest -->
        <test-method status="FAIL" signature="multTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.MultDoubleCalculatorTest@264c5d07]" name="multTest" duration-ms="1" started-at="2019-01-08T16:03:50Z" data-provider="multDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[4.77]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[4.77]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Invalid result of multiplication:  expected [4.77] but found [4.0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Invalid result of multiplication:  expected [4.77] but found [4.0]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at kz.epam.unittesting.tests.MultDoubleCalculatorTest.multTest(MultDoubleCalculatorTest.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- multTest -->
        <test-method status="PASS" signature="multTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.MultDoubleCalculatorTest@264c5d07]" name="multTest" duration-ms="1" started-at="2019-01-08T16:03:50Z" data-provider="multDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[4.1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- multTest -->
        <test-method status="PASS" signature="multTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.MultDoubleCalculatorTest@264c5d07]" name="multTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="multDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[4.1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- multTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:kz.epam.unittesting.tests.MultDoubleCalculatorTest@264c5d07]" name="tearDown" is-config="true" duration-ms="0" started-at="2019-01-08T16:03:50Z" finished-at="2019-01-08T16:03:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- kz.epam.unittesting.tests.MultDoubleCalculatorTest -->
      <class name="kz.epam.unittesting.tests.PowCalculatorTest">
        <test-method status="PASS" signature="powTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.PowCalculatorTest@30af7377]" name="powTest" duration-ms="1" started-at="2019-01-08T16:03:50Z" data-provider="pow" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[3]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[9]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- powTest -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:kz.epam.unittesting.tests.PowCalculatorTest@30af7377]" name="setUp" is-config="true" duration-ms="0" started-at="2019-01-08T16:03:50Z" finished-at="2019-01-08T16:03:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="powTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.PowCalculatorTest@30af7377]" name="powTest" duration-ms="1" started-at="2019-01-08T16:03:50Z" data-provider="pow" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[5]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[25]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- powTest -->
        <test-method status="PASS" signature="powTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.PowCalculatorTest@30af7377]" name="powTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="pow" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- powTest -->
        <test-method status="PASS" signature="powTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.PowCalculatorTest@30af7377]" name="powTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="pow" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[3]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[8]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- powTest -->
        <test-method status="PASS" signature="powTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.PowCalculatorTest@30af7377]" name="powTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="pow" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[2.2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1.1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[2.2]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- powTest -->
        <test-method status="PASS" signature="powTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.PowCalculatorTest@30af7377]" name="powTest" duration-ms="1" started-at="2019-01-08T16:03:50Z" data-provider="pow" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[-2.2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1.1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[-2.2]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- powTest -->
        <test-method status="PASS" signature="powTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.PowCalculatorTest@30af7377]" name="powTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="pow" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[3]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- powTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:kz.epam.unittesting.tests.PowCalculatorTest@30af7377]" name="tearDown" is-config="true" duration-ms="0" started-at="2019-01-08T16:03:50Z" finished-at="2019-01-08T16:03:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- kz.epam.unittesting.tests.PowCalculatorTest -->
      <class name="kz.epam.unittesting.tests.DivCalculatorTest">
        <test-method status="PASS" signature="divByZero(long)[pri:0, instance:kz.epam.unittesting.tests.DivCalculatorTest@4e868ef5]" name="divByZero" duration-ms="3" started-at="2019-01-08T16:03:50Z" data-provider="divByZeroLong" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[-4]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NumberFormatException">
            <message>
              <![CDATA[Attempt to divide by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NumberFormatException: Attempt to divide by zero
	at com.epam.tat.module4.Calculator.div(Calculator.java:34)
	at kz.epam.unittesting.tests.DivCalculatorTest.divByZero(DivCalculatorTest.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NumberFormatException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- divByZero -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:kz.epam.unittesting.tests.DivCalculatorTest@4e868ef5]" name="setUp" is-config="true" duration-ms="0" started-at="2019-01-08T16:03:50Z" finished-at="2019-01-08T16:03:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="divByZero(long)[pri:0, instance:kz.epam.unittesting.tests.DivCalculatorTest@4e868ef5]" name="divByZero" duration-ms="1" started-at="2019-01-08T16:03:50Z" data-provider="divByZeroLong" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[15]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NumberFormatException">
            <message>
              <![CDATA[Attempt to divide by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NumberFormatException: Attempt to divide by zero
	at com.epam.tat.module4.Calculator.div(Calculator.java:34)
	at kz.epam.unittesting.tests.DivCalculatorTest.divByZero(DivCalculatorTest.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NumberFormatException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- divByZero -->
        <test-method status="PASS" signature="divByZero(long)[pri:0, instance:kz.epam.unittesting.tests.DivCalculatorTest@4e868ef5]" name="divByZero" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="divByZeroLong" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[22]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NumberFormatException">
            <message>
              <![CDATA[Attempt to divide by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NumberFormatException: Attempt to divide by zero
	at com.epam.tat.module4.Calculator.div(Calculator.java:34)
	at kz.epam.unittesting.tests.DivCalculatorTest.divByZero(DivCalculatorTest.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NumberFormatException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- divByZero -->
        <test-method status="PASS" signature="divByZero(long)[pri:0, instance:kz.epam.unittesting.tests.DivCalculatorTest@4e868ef5]" name="divByZero" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="divByZeroLong" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[10249]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NumberFormatException">
            <message>
              <![CDATA[Attempt to divide by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NumberFormatException: Attempt to divide by zero
	at com.epam.tat.module4.Calculator.div(Calculator.java:34)
	at kz.epam.unittesting.tests.DivCalculatorTest.divByZero(DivCalculatorTest.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NumberFormatException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- divByZero -->
        <test-method status="PASS" signature="divByZero(long)[pri:0, instance:kz.epam.unittesting.tests.DivCalculatorTest@4e868ef5]" name="divByZero" duration-ms="1" started-at="2019-01-08T16:03:50Z" data-provider="divByZeroLong" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NumberFormatException">
            <message>
              <![CDATA[Attempt to divide by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NumberFormatException: Attempt to divide by zero
	at com.epam.tat.module4.Calculator.div(Calculator.java:34)
	at kz.epam.unittesting.tests.DivCalculatorTest.divByZero(DivCalculatorTest.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NumberFormatException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- divByZero -->
        <test-method status="PASS" signature="divTest(long, long, long)[pri:0, instance:kz.epam.unittesting.tests.DivCalculatorTest@4e868ef5]" name="divTest" duration-ms="1" started-at="2019-01-08T16:03:50Z" data-provider="divLong" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[160]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[10]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[16]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- divTest -->
        <test-method status="PASS" signature="divTest(long, long, long)[pri:0, instance:kz.epam.unittesting.tests.DivCalculatorTest@4e868ef5]" name="divTest" duration-ms="1" started-at="2019-01-08T16:03:50Z" data-provider="divLong" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[25]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[5]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[5]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- divTest -->
        <test-method status="PASS" signature="divTest(long, long, long)[pri:0, instance:kz.epam.unittesting.tests.DivCalculatorTest@4e868ef5]" name="divTest" duration-ms="2" started-at="2019-01-08T16:03:50Z" data-provider="divLong" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[-150]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[15]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[-10]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- divTest -->
        <test-method status="PASS" signature="divTest(long, long, long)[pri:0, instance:kz.epam.unittesting.tests.DivCalculatorTest@4e868ef5]" name="divTest" duration-ms="1" started-at="2019-01-08T16:03:50Z" data-provider="divLong" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[-150]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[-15]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[10]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- divTest -->
        <test-method status="PASS" signature="divTest(long, long, long)[pri:0, instance:kz.epam.unittesting.tests.DivCalculatorTest@4e868ef5]" name="divTest" duration-ms="3" started-at="2019-01-08T16:03:50Z" data-provider="divLong" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[4]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- divTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:kz.epam.unittesting.tests.DivCalculatorTest@4e868ef5]" name="tearDown" is-config="true" duration-ms="1" started-at="2019-01-08T16:03:50Z" finished-at="2019-01-08T16:03:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- kz.epam.unittesting.tests.DivCalculatorTest -->
      <class name="kz.epam.unittesting.tests.SinCalculatorTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:kz.epam.unittesting.tests.SinCalculatorTest@67a056f1]" name="setUp" is-config="true" duration-ms="1" started-at="2019-01-08T16:03:50Z" finished-at="2019-01-08T16:03:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="sinTest(double, double)[pri:0, instance:kz.epam.unittesting.tests.SinCalculatorTest@67a056f1]" name="sinTest" duration-ms="1" started-at="2019-01-08T16:03:50Z" data-provider="sin" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[45]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[0.7071067811865475]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sinTest -->
        <test-method status="PASS" signature="sinTest(double, double)[pri:0, instance:kz.epam.unittesting.tests.SinCalculatorTest@67a056f1]" name="sinTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="sin" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[60]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[0.8660254037844386]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sinTest -->
        <test-method status="PASS" signature="sinTest(double, double)[pri:0, instance:kz.epam.unittesting.tests.SinCalculatorTest@67a056f1]" name="sinTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="sin" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[90]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sinTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:kz.epam.unittesting.tests.SinCalculatorTest@67a056f1]" name="tearDown" is-config="true" duration-ms="0" started-at="2019-01-08T16:03:50Z" finished-at="2019-01-08T16:03:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- kz.epam.unittesting.tests.SinCalculatorTest -->
      <class name="kz.epam.unittesting.tests.IsPositiveCalculatorTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:kz.epam.unittesting.tests.IsPositiveCalculatorTest@175acfb2]" name="setUp" is-config="true" duration-ms="1" started-at="2019-01-08T16:03:50Z" finished-at="2019-01-08T16:03:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="isPositiveFalseTest(long)[pri:0, instance:kz.epam.unittesting.tests.IsPositiveCalculatorTest@175acfb2]" name="isPositiveFalseTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="isPositiveFalse" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- isPositiveFalseTest -->
        <test-method status="PASS" signature="isPositiveFalseTest(long)[pri:0, instance:kz.epam.unittesting.tests.IsPositiveCalculatorTest@175acfb2]" name="isPositiveFalseTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="isPositiveFalse" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[-1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- isPositiveFalseTest -->
        <test-method status="PASS" signature="isPositiveFalseTest(long)[pri:0, instance:kz.epam.unittesting.tests.IsPositiveCalculatorTest@175acfb2]" name="isPositiveFalseTest" duration-ms="7" started-at="2019-01-08T16:03:50Z" data-provider="isPositiveFalse" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[-23]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- isPositiveFalseTest -->
        <test-method status="PASS" signature="isPositiveFalseTest(long)[pri:0, instance:kz.epam.unittesting.tests.IsPositiveCalculatorTest@175acfb2]" name="isPositiveFalseTest" duration-ms="5" started-at="2019-01-08T16:03:50Z" data-provider="isPositiveFalse" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[-4003]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- isPositiveFalseTest -->
        <test-method status="PASS" signature="isPositiveFalseTest(long)[pri:0, instance:kz.epam.unittesting.tests.IsPositiveCalculatorTest@175acfb2]" name="isPositiveFalseTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="isPositiveFalse" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[-145]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- isPositiveFalseTest -->
        <test-method status="PASS" signature="isPositiveTrueTest(long)[pri:0, instance:kz.epam.unittesting.tests.IsPositiveCalculatorTest@175acfb2]" name="isPositiveTrueTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="isPositiveTrue" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- isPositiveTrueTest -->
        <test-method status="PASS" signature="isPositiveTrueTest(long)[pri:0, instance:kz.epam.unittesting.tests.IsPositiveCalculatorTest@175acfb2]" name="isPositiveTrueTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="isPositiveTrue" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[12]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- isPositiveTrueTest -->
        <test-method status="PASS" signature="isPositiveTrueTest(long)[pri:0, instance:kz.epam.unittesting.tests.IsPositiveCalculatorTest@175acfb2]" name="isPositiveTrueTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="isPositiveTrue" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[555]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- isPositiveTrueTest -->
        <test-method status="PASS" signature="isPositiveTrueTest(long)[pri:0, instance:kz.epam.unittesting.tests.IsPositiveCalculatorTest@175acfb2]" name="isPositiveTrueTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="isPositiveTrue" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1234]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- isPositiveTrueTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:kz.epam.unittesting.tests.IsPositiveCalculatorTest@175acfb2]" name="tearDown" is-config="true" duration-ms="1" started-at="2019-01-08T16:03:50Z" finished-at="2019-01-08T16:03:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="isPositiveTrueTest(long)[pri:0, instance:kz.epam.unittesting.tests.IsPositiveCalculatorTest@175acfb2]" name="isPositiveTrueTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="isPositiveTrue" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[75644]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- isPositiveTrueTest -->
        <test-method status="PASS" signature="isPositiveTrueTest(long)[pri:0, instance:kz.epam.unittesting.tests.IsPositiveCalculatorTest@175acfb2]" name="isPositiveTrueTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="isPositiveTrue" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[324324]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- isPositiveTrueTest -->
      </class> <!-- kz.epam.unittesting.tests.IsPositiveCalculatorTest -->
      <class name="kz.epam.unittesting.tests.CtgCalculatorTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:kz.epam.unittesting.tests.CtgCalculatorTest@1dab9dd6]" name="setUp" is-config="true" duration-ms="0" started-at="2019-01-08T16:03:50Z" finished-at="2019-01-08T16:03:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="ctgTest(double, double)[pri:0, instance:kz.epam.unittesting.tests.CtgCalculatorTest@1dab9dd6]" name="ctgTest" duration-ms="1" started-at="2019-01-08T16:03:50Z" data-provider="ctg" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[30.0]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1.732]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Invalid result of ctangent:  expected [1.732] but found [0.4804727781564516]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Invalid result of ctangent:  expected [1.732] but found [0.4804727781564516]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at kz.epam.unittesting.tests.CtgCalculatorTest.ctgTest(CtgCalculatorTest.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ctgTest -->
        <test-method status="FAIL" signature="ctgTest(double, double)[pri:0, instance:kz.epam.unittesting.tests.CtgCalculatorTest@1dab9dd6]" name="ctgTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="ctg" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[45]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Invalid result of ctangent:  expected [1.0] but found [0.6557942026326724]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Invalid result of ctangent:  expected [1.0] but found [0.6557942026326724]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at kz.epam.unittesting.tests.CtgCalculatorTest.ctgTest(CtgCalculatorTest.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ctgTest -->
        <test-method status="FAIL" signature="ctgTest(double, double)[pri:0, instance:kz.epam.unittesting.tests.CtgCalculatorTest@1dab9dd6]" name="ctgTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="ctg" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[60.0]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[0.577]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Invalid result of ctangent:  expected [0.577] but found [0.7807144353592677]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Invalid result of ctangent:  expected [0.577] but found [0.7807144353592677]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at kz.epam.unittesting.tests.CtgCalculatorTest.ctgTest(CtgCalculatorTest.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ctgTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:kz.epam.unittesting.tests.CtgCalculatorTest@1dab9dd6]" name="tearDown" is-config="true" duration-ms="1" started-at="2019-01-08T16:03:50Z" finished-at="2019-01-08T16:03:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- kz.epam.unittesting.tests.CtgCalculatorTest -->
      <class name="kz.epam.unittesting.tests.SubDoubleCalculatorTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:kz.epam.unittesting.tests.SubDoubleCalculatorTest@5e742e4]" name="setUp" is-config="true" duration-ms="1" started-at="2019-01-08T16:03:50Z" finished-at="2019-01-08T16:03:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="subDoubleTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.SubDoubleCalculatorTest@5e742e4]" name="subDoubleTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="subDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[214.5]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[305.5]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[-91]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- subDoubleTest -->
        <test-method status="PASS" signature="subDoubleTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.SubDoubleCalculatorTest@5e742e4]" name="subDoubleTest" duration-ms="3" started-at="2019-01-08T16:03:50Z" data-provider="subDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[25.9]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[14.7]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[11.2]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- subDoubleTest -->
        <test-method status="PASS" signature="subDoubleTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.SubDoubleCalculatorTest@5e742e4]" name="subDoubleTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="subDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[75.45]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[25.34]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[50.11]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- subDoubleTest -->
        <test-method status="FAIL" signature="subDoubleTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.SubDoubleCalculatorTest@5e742e4]" name="subDoubleTest" duration-ms="1" started-at="2019-01-08T16:03:50Z" data-provider="subDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[100.01]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[64]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[36.01]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Invalid result of subtraction:  expected [36.01] but found [36.010000000000005]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Invalid result of subtraction:  expected [36.01] but found [36.010000000000005]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at kz.epam.unittesting.tests.SubDoubleCalculatorTest.subDoubleTest(SubDoubleCalculatorTest.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- subDoubleTest -->
        <test-method status="FAIL" signature="subDoubleTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.SubDoubleCalculatorTest@5e742e4]" name="subDoubleTest" duration-ms="1" started-at="2019-01-08T16:03:50Z" data-provider="subDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[100.1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[64.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[36.1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Invalid result of subtraction:  expected [36.1] but found [36.099999999999994]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Invalid result of subtraction:  expected [36.1] but found [36.099999999999994]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at kz.epam.unittesting.tests.SubDoubleCalculatorTest.subDoubleTest(SubDoubleCalculatorTest.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- subDoubleTest -->
        <test-method status="FAIL" signature="subDoubleTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.SubDoubleCalculatorTest@5e742e4]" name="subDoubleTest" duration-ms="1" started-at="2019-01-08T16:03:50Z" data-provider="subDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[100.4]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[64.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[36.4]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Invalid result of subtraction:  expected [36.4] but found [36.400000000000006]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Invalid result of subtraction:  expected [36.4] but found [36.400000000000006]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at kz.epam.unittesting.tests.SubDoubleCalculatorTest.subDoubleTest(SubDoubleCalculatorTest.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- subDoubleTest -->
        <test-method status="FAIL" signature="subDoubleTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.SubDoubleCalculatorTest@5e742e4]" name="subDoubleTest" duration-ms="1" started-at="2019-01-08T16:03:50Z" data-provider="subDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[100.6]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[64.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[36.6]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Invalid result of subtraction:  expected [36.6] but found [36.599999999999994]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Invalid result of subtraction:  expected [36.6] but found [36.599999999999994]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at kz.epam.unittesting.tests.SubDoubleCalculatorTest.subDoubleTest(SubDoubleCalculatorTest.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- subDoubleTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:kz.epam.unittesting.tests.SubDoubleCalculatorTest@5e742e4]" name="tearDown" is-config="true" duration-ms="1" started-at="2019-01-08T16:03:50Z" finished-at="2019-01-08T16:03:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="subDoubleTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.SubDoubleCalculatorTest@5e742e4]" name="subDoubleTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="subDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[100.9]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[64.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[36.9]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Invalid result of subtraction:  expected [36.9] but found [36.900000000000006]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Invalid result of subtraction:  expected [36.9] but found [36.900000000000006]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at kz.epam.unittesting.tests.SubDoubleCalculatorTest.subDoubleTest(SubDoubleCalculatorTest.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- subDoubleTest -->
      </class> <!-- kz.epam.unittesting.tests.SubDoubleCalculatorTest -->
      <class name="kz.epam.unittesting.tests.SumDoubleCalculatorTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:kz.epam.unittesting.tests.SumDoubleCalculatorTest@4a03bb68]" name="setUp" is-config="true" duration-ms="0" started-at="2019-01-08T16:03:50Z" finished-at="2019-01-08T16:03:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="sumDoubleTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.SumDoubleCalculatorTest@4a03bb68]" name="sumDoubleTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="sumDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[214.5]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[305.5]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[520]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sumDoubleTest -->
        <test-method status="PASS" signature="sumDoubleTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.SumDoubleCalculatorTest@4a03bb68]" name="sumDoubleTest" duration-ms="4" started-at="2019-01-08T16:03:50Z" data-provider="sumDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[10.1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[10.3]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[20.4]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sumDoubleTest -->
        <test-method status="PASS" signature="sumDoubleTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.SumDoubleCalculatorTest@4a03bb68]" name="sumDoubleTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="sumDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[44.0]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[16]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[60]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sumDoubleTest -->
        <test-method status="PASS" signature="sumDoubleTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.SumDoubleCalculatorTest@4a03bb68]" name="sumDoubleTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="sumDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[44.9]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[16.1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[61]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sumDoubleTest -->
        <test-method status="PASS" signature="sumDoubleTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.SumDoubleCalculatorTest@4a03bb68]" name="sumDoubleTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="sumDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[44.7]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[16]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[60.7]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sumDoubleTest -->
        <test-method status="PASS" signature="sumDoubleTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.SumDoubleCalculatorTest@4a03bb68]" name="sumDoubleTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="sumDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[-16.0]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[-44.1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[-60.1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sumDoubleTest -->
        <test-method status="PASS" signature="sumDoubleTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.SumDoubleCalculatorTest@4a03bb68]" name="sumDoubleTest" duration-ms="1" started-at="2019-01-08T16:03:50Z" data-provider="sumDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[16.0]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[-44.9]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[-28.9]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sumDoubleTest -->
        <test-method status="PASS" signature="sumDoubleTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.SumDoubleCalculatorTest@4a03bb68]" name="sumDoubleTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="sumDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[-16.0]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[44.9]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[28.9]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sumDoubleTest -->
        <test-method status="FAIL" signature="sumDoubleTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.SumDoubleCalculatorTest@4a03bb68]" name="sumDoubleTest" duration-ms="2" started-at="2019-01-08T16:03:50Z" data-provider="sumDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[16.0]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[-44.7]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[-28.7]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Invalid result of sum: expected [-28.7] but found [-28.700000000000003]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Invalid result of sum: expected [-28.7] but found [-28.700000000000003]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at kz.epam.unittesting.tests.SumDoubleCalculatorTest.sumDoubleTest(SumDoubleCalculatorTest.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sumDoubleTest -->
        <test-method status="FAIL" signature="sumDoubleTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.SumDoubleCalculatorTest@4a03bb68]" name="sumDoubleTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="sumDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[16.0]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[-44.8]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[-28.8]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Invalid result of sum: expected [-28.8] but found [-28.799999999999997]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Invalid result of sum: expected [-28.8] but found [-28.799999999999997]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at kz.epam.unittesting.tests.SumDoubleCalculatorTest.sumDoubleTest(SumDoubleCalculatorTest.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sumDoubleTest -->
        <test-method status="PASS" signature="sumDoubleTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.SumDoubleCalculatorTest@4a03bb68]" name="sumDoubleTest" duration-ms="1" started-at="2019-01-08T16:03:50Z" data-provider="sumDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[16.0]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[-44.6]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[-28.6]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sumDoubleTest -->
        <test-method status="PASS" signature="sumDoubleTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.SumDoubleCalculatorTest@4a03bb68]" name="sumDoubleTest" duration-ms="2" started-at="2019-01-08T16:03:50Z" data-provider="sumDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[16.0]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[-44.4]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[-28.4]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sumDoubleTest -->
        <test-method status="PASS" signature="sumDoubleTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.SumDoubleCalculatorTest@4a03bb68]" name="sumDoubleTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="sumDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[16.0]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[-44.5]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[-28.5]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sumDoubleTest -->
        <test-method status="FAIL" signature="sumDoubleTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.SumDoubleCalculatorTest@4a03bb68]" name="sumDoubleTest" duration-ms="1" started-at="2019-01-08T16:03:50Z" data-provider="sumDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[16.0]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[-44.3]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[-28.3]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Invalid result of sum: expected [-28.3] but found [-28.299999999999997]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Invalid result of sum: expected [-28.3] but found [-28.299999999999997]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at kz.epam.unittesting.tests.SumDoubleCalculatorTest.sumDoubleTest(SumDoubleCalculatorTest.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sumDoubleTest -->
        <test-method status="FAIL" signature="sumDoubleTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.SumDoubleCalculatorTest@4a03bb68]" name="sumDoubleTest" duration-ms="1" started-at="2019-01-08T16:03:50Z" data-provider="sumDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[16.0]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[-44.2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[-28.2]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Invalid result of sum: expected [-28.2] but found [-28.200000000000003]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Invalid result of sum: expected [-28.2] but found [-28.200000000000003]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at kz.epam.unittesting.tests.SumDoubleCalculatorTest.sumDoubleTest(SumDoubleCalculatorTest.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sumDoubleTest -->
        <test-method status="FAIL" signature="sumDoubleTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.SumDoubleCalculatorTest@4a03bb68]" name="sumDoubleTest" duration-ms="2" started-at="2019-01-08T16:03:50Z" data-provider="sumDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[16.0]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[-44.7]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[-28.1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Invalid result of sum: expected [-28.1] but found [-28.700000000000003]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Invalid result of sum: expected [-28.1] but found [-28.700000000000003]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at kz.epam.unittesting.tests.SumDoubleCalculatorTest.sumDoubleTest(SumDoubleCalculatorTest.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sumDoubleTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:kz.epam.unittesting.tests.SumDoubleCalculatorTest@4a03bb68]" name="tearDown" is-config="true" duration-ms="1" started-at="2019-01-08T16:03:50Z" finished-at="2019-01-08T16:03:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- kz.epam.unittesting.tests.SumDoubleCalculatorTest -->
      <class name="kz.epam.unittesting.tests.CosCalculatorTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:kz.epam.unittesting.tests.CosCalculatorTest@71c905a3]" name="setUp" is-config="true" duration-ms="20" started-at="2019-01-08T16:03:50Z" finished-at="2019-01-08T16:03:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="cosTest(double, double)[pri:0, instance:kz.epam.unittesting.tests.CosCalculatorTest@71c905a3]" name="cosTest" duration-ms="11" started-at="2019-01-08T16:03:50Z" data-provider="cos" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[0.54030230586814]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Invalid result of cos:  expected [0.54030230586814] but found [0.01745240643728351]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Invalid result of cos:  expected [0.54030230586814] but found [0.01745240643728351]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at kz.epam.unittesting.tests.CosCalculatorTest.cosTest(CosCalculatorTest.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cosTest -->
        <test-method status="FAIL" signature="cosTest(double, double)[pri:0, instance:kz.epam.unittesting.tests.CosCalculatorTest@71c905a3]" name="cosTest" duration-ms="3" started-at="2019-01-08T16:03:50Z" data-provider="cos" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[50]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[0.96496602849211]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Invalid result of cos:  expected [0.96496602849211] but found [0.766044443118978]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Invalid result of cos:  expected [0.96496602849211] but found [0.766044443118978]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at kz.epam.unittesting.tests.CosCalculatorTest.cosTest(CosCalculatorTest.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cosTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:kz.epam.unittesting.tests.CosCalculatorTest@71c905a3]" name="tearDown" is-config="true" duration-ms="1" started-at="2019-01-08T16:03:50Z" finished-at="2019-01-08T16:03:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- kz.epam.unittesting.tests.CosCalculatorTest -->
      <class name="kz.epam.unittesting.tests.SubCalculatorTest">
        <test-method status="PASS" signature="beforeGroup()[pri:0, instance:kz.epam.unittesting.tests.SubCalculatorTest@61d01788]" name="beforeGroup" is-config="true" duration-ms="0" started-at="2019-01-08T16:03:50Z" finished-at="2019-01-08T16:03:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeGroup -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:kz.epam.unittesting.tests.SubCalculatorTest@61d01788]" name="setUp" is-config="true" duration-ms="0" started-at="2019-01-08T16:03:50Z" finished-at="2019-01-08T16:03:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="subTest(long, long, long)[pri:0, instance:kz.epam.unittesting.tests.SubCalculatorTest@61d01788]" name="subTest" duration-ms="2" started-at="2019-01-08T16:03:50Z" data-provider="subLong" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[16]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[15]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- subTest -->
        <test-method status="PASS" signature="subTest(long, long, long)[pri:0, instance:kz.epam.unittesting.tests.SubCalculatorTest@61d01788]" name="subTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="subLong" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[15]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[15]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- subTest -->
        <test-method status="PASS" signature="subTest(long, long, long)[pri:0, instance:kz.epam.unittesting.tests.SubCalculatorTest@61d01788]" name="subTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="subLong" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[-10]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[-15]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[5]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- subTest -->
        <test-method status="PASS" signature="subTest(long, long, long)[pri:0, instance:kz.epam.unittesting.tests.SubCalculatorTest@61d01788]" name="subTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="subLong" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[10]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[-15]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[25]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- subTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:kz.epam.unittesting.tests.SubCalculatorTest@61d01788]" name="tearDown" is-config="true" duration-ms="0" started-at="2019-01-08T16:03:50Z" finished-at="2019-01-08T16:03:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="subTest(long, long, long)[pri:0, instance:kz.epam.unittesting.tests.SubCalculatorTest@61d01788]" name="subTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="subLong" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[-10]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[15]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[-25]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- subTest -->
        <test-method status="PASS" signature="beforeGroup()[pri:0, instance:kz.epam.unittesting.tests.SubCalculatorTest@61d01788]" name="beforeGroup" is-config="true" duration-ms="0" started-at="2019-01-08T16:03:50Z" finished-at="2019-01-08T16:03:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeGroup -->
      </class> <!-- kz.epam.unittesting.tests.SubCalculatorTest -->
      <class name="kz.epam.unittesting.tests.TgCalculatorTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:kz.epam.unittesting.tests.TgCalculatorTest@2b9b7f1f]" name="setUp" is-config="true" duration-ms="2" started-at="2019-01-08T16:03:50Z" finished-at="2019-01-08T16:03:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="tgTest(double, double)[pri:0, instance:kz.epam.unittesting.tests.TgCalculatorTest@2b9b7f1f]" name="tgTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="tg" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[30.0]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[0.5774]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Invalid result of tangent:  expected [0.5774] but found [1.0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Invalid result of tangent:  expected [0.5774] but found [1.0]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at kz.epam.unittesting.tests.TgCalculatorTest.tgTest(TgCalculatorTest.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tgTest -->
        <test-method status="PASS" signature="tgTest(double, double)[pri:0, instance:kz.epam.unittesting.tests.TgCalculatorTest@2b9b7f1f]" name="tgTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="tg" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[45]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tgTest -->
        <test-method status="FAIL" signature="tgTest(double, double)[pri:0, instance:kz.epam.unittesting.tests.TgCalculatorTest@2b9b7f1f]" name="tgTest" duration-ms="5" started-at="2019-01-08T16:03:50Z" data-provider="tg" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[60.0]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1.7321]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Invalid result of tangent:  expected [1.7321] but found [1.0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Invalid result of tangent:  expected [1.7321] but found [1.0]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at kz.epam.unittesting.tests.TgCalculatorTest.tgTest(TgCalculatorTest.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tgTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:kz.epam.unittesting.tests.TgCalculatorTest@2b9b7f1f]" name="tearDown" is-config="true" duration-ms="0" started-at="2019-01-08T16:03:50Z" finished-at="2019-01-08T16:03:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- kz.epam.unittesting.tests.TgCalculatorTest -->
      <class name="kz.epam.unittesting.tests.IsNegativeCalculatorTest">
        <test-method status="PASS" signature="isNegativeTest(long, boolean)[pri:0, instance:kz.epam.unittesting.tests.IsNegativeCalculatorTest@69cac930]" name="isNegativeTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="isNegative" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[11]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[false]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- isNegativeTest -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:kz.epam.unittesting.tests.IsNegativeCalculatorTest@69cac930]" name="setUp" is-config="true" duration-ms="0" started-at="2019-01-08T16:03:50Z" finished-at="2019-01-08T16:03:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="isNegativeTest(long, boolean)[pri:0, instance:kz.epam.unittesting.tests.IsNegativeCalculatorTest@69cac930]" name="isNegativeTest" duration-ms="1" started-at="2019-01-08T16:03:50Z" data-provider="isNegative" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[-1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- isNegativeTest -->
        <test-method status="PASS" signature="isNegativeTest(long, boolean)[pri:0, instance:kz.epam.unittesting.tests.IsNegativeCalculatorTest@69cac930]" name="isNegativeTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="isNegative" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[false]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- isNegativeTest -->
        <test-method status="PASS" signature="isNegativeTest(long, boolean)[pri:0, instance:kz.epam.unittesting.tests.IsNegativeCalculatorTest@69cac930]" name="isNegativeTest" duration-ms="1" started-at="2019-01-08T16:03:50Z" data-provider="isNegative" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[-111]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- isNegativeTest -->
        <test-method status="PASS" signature="isNegativeTest(long, boolean)[pri:0, instance:kz.epam.unittesting.tests.IsNegativeCalculatorTest@69cac930]" name="isNegativeTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="isNegative" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[-23345]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- isNegativeTest -->
        <test-method status="PASS" signature="isNegativeTest(long, boolean)[pri:0, instance:kz.epam.unittesting.tests.IsNegativeCalculatorTest@69cac930]" name="isNegativeTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="isNegative" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[-555555]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- isNegativeTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:kz.epam.unittesting.tests.IsNegativeCalculatorTest@69cac930]" name="tearDown" is-config="true" duration-ms="0" started-at="2019-01-08T16:03:50Z" finished-at="2019-01-08T16:03:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- kz.epam.unittesting.tests.IsNegativeCalculatorTest -->
      <class name="kz.epam.unittesting.tests.SumCalculatorTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:kz.epam.unittesting.tests.SumCalculatorTest@19593091]" name="setUp" is-config="true" duration-ms="0" started-at="2019-01-08T16:03:50Z" finished-at="2019-01-08T16:03:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testSum(long, long, long)[pri:0, instance:kz.epam.unittesting.tests.SumCalculatorTest@19593091]" name="testSum" duration-ms="1" started-at="2019-01-08T16:03:50Z" data-provider="sumLong" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[3]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[5]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSum -->
        <test-method status="PASS" signature="testSum(long, long, long)[pri:0, instance:kz.epam.unittesting.tests.SumCalculatorTest@19593091]" name="testSum" duration-ms="1" started-at="2019-01-08T16:03:50Z" data-provider="sumLong" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[4]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSum -->
        <test-method status="PASS" signature="testSum(long, long, long)[pri:0, instance:kz.epam.unittesting.tests.SumCalculatorTest@19593091]" name="testSum" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="sumLong" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSum -->
        <test-method name="testSum1" signature="testSum1(long, long, long)[pri:0, instance:kz.epam.unittesting.tests.SumCalculatorTest@19593091]" depends-on-groups="group 1" status="PASS" duration-ms="0" finished-at="2019-01-08T16:03:50Z" started-at="2019-01-08T16:03:50Z" depends-on-methods="kz.epam.unittesting.tests.SumCalculatorTest.testSum" data-provider="sumLong1">
          <params>
            <param index="0">
              <value>
                <![CDATA[214]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[305]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[519]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSum1 -->
        <test-method name="testSum1" signature="testSum1(long, long, long)[pri:0, instance:kz.epam.unittesting.tests.SumCalculatorTest@19593091]" depends-on-groups="group 1" status="PASS" duration-ms="3" finished-at="2019-01-08T16:03:50Z" started-at="2019-01-08T16:03:50Z" depends-on-methods="kz.epam.unittesting.tests.SumCalculatorTest.testSum" data-provider="sumLong1">
          <params>
            <param index="0">
              <value>
                <![CDATA[10]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[10]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[20]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSum1 -->
        <test-method name="testSum1" signature="testSum1(long, long, long)[pri:0, instance:kz.epam.unittesting.tests.SumCalculatorTest@19593091]" depends-on-groups="group 1" status="PASS" duration-ms="0" finished-at="2019-01-08T16:03:50Z" started-at="2019-01-08T16:03:50Z" depends-on-methods="kz.epam.unittesting.tests.SumCalculatorTest.testSum" data-provider="sumLong1">
          <params>
            <param index="0">
              <value>
                <![CDATA[44]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[6]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[50]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSum1 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:kz.epam.unittesting.tests.SumCalculatorTest@19593091]" name="tearDown" is-config="true" duration-ms="1" started-at="2019-01-08T16:03:50Z" finished-at="2019-01-08T16:03:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- kz.epam.unittesting.tests.SumCalculatorTest -->
      <class name="kz.epam.unittesting.tests.MultCalculatorTest">
        <test-method status="PASS" signature="multTest(long, long, long)[pri:0, instance:kz.epam.unittesting.tests.MultCalculatorTest@847f3e7]" name="multTest" duration-ms="1" started-at="2019-01-08T16:03:50Z" data-provider="multLong" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[16]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[10]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[160]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- multTest -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:kz.epam.unittesting.tests.MultCalculatorTest@847f3e7]" name="setUp" is-config="true" duration-ms="0" started-at="2019-01-08T16:03:50Z" finished-at="2019-01-08T16:03:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="multTest(long, long, long)[pri:0, instance:kz.epam.unittesting.tests.MultCalculatorTest@847f3e7]" name="multTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="multLong" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[5]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[5]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[25]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- multTest -->
        <test-method status="PASS" signature="multTest(long, long, long)[pri:0, instance:kz.epam.unittesting.tests.MultCalculatorTest@847f3e7]" name="multTest" duration-ms="1" started-at="2019-01-08T16:03:50Z" data-provider="multLong" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[10]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[-15]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[-150]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- multTest -->
        <test-method status="PASS" signature="multTest(long, long, long)[pri:0, instance:kz.epam.unittesting.tests.MultCalculatorTest@847f3e7]" name="multTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="multLong" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[-10]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[-15]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[150]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- multTest -->
        <test-method status="PASS" signature="multTest(long, long, long)[pri:0, instance:kz.epam.unittesting.tests.MultCalculatorTest@847f3e7]" name="multTest" duration-ms="2" started-at="2019-01-08T16:03:50Z" data-provider="multLong" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[4]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- multTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:kz.epam.unittesting.tests.MultCalculatorTest@847f3e7]" name="tearDown" is-config="true" duration-ms="1" started-at="2019-01-08T16:03:50Z" finished-at="2019-01-08T16:03:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- kz.epam.unittesting.tests.MultCalculatorTest -->
      <class name="kz.epam.unittesting.tests.DivDoubleCalculatorTest">
        <test-method status="FAIL" signature="divByZeroTest(double)[pri:0, instance:kz.epam.unittesting.tests.DivDoubleCalculatorTest@6ad6fa53]" name="divByZeroTest" duration-ms="1" started-at="2019-01-08T16:03:50Z" data-provider="divByZeroDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[-4.2]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Method DivDoubleCalculatorTest.divByZeroTest(double)[pri:0, instance:kz.epam.unittesting.tests.DivDoubleCalculatorTest@6ad6fa53] should have thrown an exception of type class java.lang.ArithmeticException]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Method DivDoubleCalculatorTest.divByZeroTest(double)[pri:0, instance:kz.epam.unittesting.tests.DivDoubleCalculatorTest@6ad6fa53] should have thrown an exception of type class java.lang.ArithmeticException
	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:89)
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1416)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:695)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- divByZeroTest -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:kz.epam.unittesting.tests.DivDoubleCalculatorTest@6ad6fa53]" name="setUp" is-config="true" duration-ms="0" started-at="2019-01-08T16:03:50Z" finished-at="2019-01-08T16:03:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="divByZeroTest(double)[pri:0, instance:kz.epam.unittesting.tests.DivDoubleCalculatorTest@6ad6fa53]" name="divByZeroTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="divByZeroDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[0.0233]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Method DivDoubleCalculatorTest.divByZeroTest(double)[pri:0, instance:kz.epam.unittesting.tests.DivDoubleCalculatorTest@6ad6fa53] should have thrown an exception of type class java.lang.ArithmeticException]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Method DivDoubleCalculatorTest.divByZeroTest(double)[pri:0, instance:kz.epam.unittesting.tests.DivDoubleCalculatorTest@6ad6fa53] should have thrown an exception of type class java.lang.ArithmeticException
	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:89)
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1416)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:695)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- divByZeroTest -->
        <test-method status="FAIL" signature="divByZeroTest(double)[pri:0, instance:kz.epam.unittesting.tests.DivDoubleCalculatorTest@6ad6fa53]" name="divByZeroTest" duration-ms="1" started-at="2019-01-08T16:03:50Z" data-provider="divByZeroDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[-4.2]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Method DivDoubleCalculatorTest.divByZeroTest(double)[pri:0, instance:kz.epam.unittesting.tests.DivDoubleCalculatorTest@6ad6fa53] should have thrown an exception of type class java.lang.ArithmeticException]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Method DivDoubleCalculatorTest.divByZeroTest(double)[pri:0, instance:kz.epam.unittesting.tests.DivDoubleCalculatorTest@6ad6fa53] should have thrown an exception of type class java.lang.ArithmeticException
	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:89)
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1416)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:695)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- divByZeroTest -->
        <test-method status="FAIL" signature="divByZeroTest(double)[pri:0, instance:kz.epam.unittesting.tests.DivDoubleCalculatorTest@6ad6fa53]" name="divByZeroTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="divByZeroDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[0.0]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Method DivDoubleCalculatorTest.divByZeroTest(double)[pri:0, instance:kz.epam.unittesting.tests.DivDoubleCalculatorTest@6ad6fa53] should have thrown an exception of type class java.lang.ArithmeticException]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Method DivDoubleCalculatorTest.divByZeroTest(double)[pri:0, instance:kz.epam.unittesting.tests.DivDoubleCalculatorTest@6ad6fa53] should have thrown an exception of type class java.lang.ArithmeticException
	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:89)
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1416)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:695)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- divByZeroTest -->
        <test-method status="FAIL" signature="divByZeroTest(double)[pri:0, instance:kz.epam.unittesting.tests.DivDoubleCalculatorTest@6ad6fa53]" name="divByZeroTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="divByZeroDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[566]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Method DivDoubleCalculatorTest.divByZeroTest(double)[pri:0, instance:kz.epam.unittesting.tests.DivDoubleCalculatorTest@6ad6fa53] should have thrown an exception of type class java.lang.ArithmeticException]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Method DivDoubleCalculatorTest.divByZeroTest(double)[pri:0, instance:kz.epam.unittesting.tests.DivDoubleCalculatorTest@6ad6fa53] should have thrown an exception of type class java.lang.ArithmeticException
	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:89)
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1416)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:695)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- divByZeroTest -->
        <test-method status="FAIL" signature="divByZeroTest(double)[pri:0, instance:kz.epam.unittesting.tests.DivDoubleCalculatorTest@6ad6fa53]" name="divByZeroTest" duration-ms="1" started-at="2019-01-08T16:03:50Z" data-provider="divByZeroDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[0.001]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Method DivDoubleCalculatorTest.divByZeroTest(double)[pri:0, instance:kz.epam.unittesting.tests.DivDoubleCalculatorTest@6ad6fa53] should have thrown an exception of type class java.lang.ArithmeticException]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Method DivDoubleCalculatorTest.divByZeroTest(double)[pri:0, instance:kz.epam.unittesting.tests.DivDoubleCalculatorTest@6ad6fa53] should have thrown an exception of type class java.lang.ArithmeticException
	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:89)
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1416)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:695)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- divByZeroTest -->
        <test-method status="PASS" signature="divTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.DivDoubleCalculatorTest@6ad6fa53]" name="divTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="divDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[2.2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[1.1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- divTest -->
        <test-method status="PASS" signature="divTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.DivDoubleCalculatorTest@6ad6fa53]" name="divTest" duration-ms="1" started-at="2019-01-08T16:03:50Z" data-provider="divDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[30.25]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[5.5]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[5.5]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- divTest -->
        <test-method status="PASS" signature="divTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.DivDoubleCalculatorTest@6ad6fa53]" name="divTest" duration-ms="1" started-at="2019-01-08T16:03:50Z" data-provider="divDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[151]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[-15.1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[-10]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- divTest -->
        <test-method status="PASS" signature="divTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.DivDoubleCalculatorTest@6ad6fa53]" name="divTest" duration-ms="3" started-at="2019-01-08T16:03:50Z" data-provider="divDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[-150]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[-15]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[10]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- divTest -->
        <test-method status="PASS" signature="divTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.DivDoubleCalculatorTest@6ad6fa53]" name="divTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="divDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[4.77]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[4.77]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- divTest -->
        <test-method status="PASS" signature="divTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.DivDoubleCalculatorTest@6ad6fa53]" name="divTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="divDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[22.8006]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[4.78]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[4.77]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- divTest -->
        <test-method status="PASS" signature="divTest(double, double, double)[pri:0, instance:kz.epam.unittesting.tests.DivDoubleCalculatorTest@6ad6fa53]" name="divTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="divDouble" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[4]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- divTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:kz.epam.unittesting.tests.DivDoubleCalculatorTest@6ad6fa53]" name="tearDown" is-config="true" duration-ms="0" started-at="2019-01-08T16:03:50Z" finished-at="2019-01-08T16:03:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- kz.epam.unittesting.tests.DivDoubleCalculatorTest -->
      <class name="kz.epam.unittesting.tests.SqrtCalculatorTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:kz.epam.unittesting.tests.SqrtCalculatorTest@55ea2d70]" name="setUp" is-config="true" duration-ms="0" started-at="2019-01-08T16:03:50Z" finished-at="2019-01-08T16:03:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="sqrtTest(double, double)[pri:0, instance:kz.epam.unittesting.tests.SqrtCalculatorTest@55ea2d70]" name="sqrtTest" duration-ms="1" started-at="2019-01-08T16:03:50Z" data-provider="sqrt" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[9]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[3]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sqrtTest -->
        <test-method status="PASS" signature="sqrtTest(double, double)[pri:0, instance:kz.epam.unittesting.tests.SqrtCalculatorTest@55ea2d70]" name="sqrtTest" duration-ms="1" started-at="2019-01-08T16:03:50Z" data-provider="sqrt" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[4]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sqrtTest -->
        <test-method status="PASS" signature="sqrtTest(double, double)[pri:0, instance:kz.epam.unittesting.tests.SqrtCalculatorTest@55ea2d70]" name="sqrtTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="sqrt" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[49]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[7]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sqrtTest -->
        <test-method status="PASS" signature="sqrtTest(double, double)[pri:0, instance:kz.epam.unittesting.tests.SqrtCalculatorTest@55ea2d70]" name="sqrtTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="sqrt" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1.21]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1.1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sqrtTest -->
        <test-method status="PASS" signature="sqrtTest(double, double)[pri:0, instance:kz.epam.unittesting.tests.SqrtCalculatorTest@55ea2d70]" name="sqrtTest" duration-ms="1" started-at="2019-01-08T16:03:50Z" data-provider="sqrt" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sqrtTest -->
        <test-method status="PASS" signature="sqrtTest(double, double)[pri:0, instance:kz.epam.unittesting.tests.SqrtCalculatorTest@55ea2d70]" name="sqrtTest" duration-ms="0" started-at="2019-01-08T16:03:50Z" data-provider="sqrt" finished-at="2019-01-08T16:03:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[-49]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[7]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sqrtTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:kz.epam.unittesting.tests.SqrtCalculatorTest@55ea2d70]" name="tearDown" is-config="true" duration-ms="0" started-at="2019-01-08T16:03:50Z" finished-at="2019-01-08T16:03:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- kz.epam.unittesting.tests.SqrtCalculatorTest -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
